### ISSUE TITLE
Starting Rails Console in production environment errors out

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/trove#218]
@jcoyne Is this a known issue or am I doing something incorrect?  It happens on both my laptop and our prod server. 

```
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:5: warning: already initialized constant Hydra::AccessControls::AccessRight::PERMISSION_TEXT_VALUE_PUBLIC
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:5: warning: previous definition of PERMISSION_TEXT_VALUE_PUBLIC was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:6: warning: already initialized constant Hydra::AccessControls::AccessRight::PERMISSION_TEXT_VALUE_AUTHENTICATED
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:6: warning: previous definition of PERMISSION_TEXT_VALUE_AUTHENTICATED was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:9: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:9: warning: previous definition of VISIBILITY_TEXT_VALUE_PUBLIC was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:10: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_EMBARGO
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:10: warning: previous definition of VISIBILITY_TEXT_VALUE_EMBARGO was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:11: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_LEASE
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:11: warning: previous definition of VISIBILITY_TEXT_VALUE_LEASE was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:12: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_AUTHENTICATED
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:12: warning: previous definition of VISIBILITY_TEXT_VALUE_AUTHENTICATED was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:13: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PRIVATE
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/access_right.rb:13: warning: previous definition of VISIBILITY_TEXT_VALUE_PRIVATE was here
/home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/embargoable.rb:6:in `<module:Embargoable>'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/embargoable.rb:3:in `<module:AccessControls>'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/embargoable.rb:2:in `<module:Hydra>'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/hydra-access-controls-7.2.2/app/models/concerns/hydra/access_controls/embargoable.rb:1:in `<top (required)>'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:443:in `load'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:443:in `block in load_file'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:633:in `new_constants_in'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:442:in `load_file'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:342:in `require_or_load'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:307:in `depend_on'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:225:in `require_dependency'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/engine.rb:467:in `each'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/engine.rb:467:in `block in eager_load!'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/engine.rb:465:in `each'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/engine.rb:465:in `eager_load!'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/engine.rb:346:in `eager_load!'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/application/finisher.rb:58:in `each'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
	from /home/hydradm/tufts-image-library/config/environment.rb:5:in `<top (required)>'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/spring-1.1.3/lib/spring/application.rb:92:in `preload'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/spring-1.1.3/lib/spring/application.rb:140:in `serve'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
	from /home/hydradm/.rvm/gems/ruby-2.1.2@tdil/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/hydradm/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by mkorcy** [comment]
with environment set to development, its fine btw.

**Comment by jcoyne** [comment]
You've installed the spring gem into your production environment. You can't do that. See https://github.com/rails/spring/issues/318.

You need to `bundle install --without development`

**Comment by mkorcy** [comment]
Thanks.
